apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsgICAgCiAgICAgImdoY3IuaW8iOiB7CiAgICAgICJhdXRoIjogImEybHdjbTlyYjNCbGJtdHZPbWRvY0Y5elRtbFVlRXA0ZDNBd2NVUm9RbmhpTkc5cGFHUjJWa2gwZW14bmVHb3piMmxJIgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
