apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJhMmx3Y205cmIzQmxibXR2T21kcGRHaDFZbDl3WVhSZk1URkJWMWRHVFZOUk1FaE1TazVvVVRWV01uWXdNVjlTYTFoV2FWZzFUR0pqV0ZSbFlVVjJWRzFpUzBkVmFtOW5iWGxKWkVselV6Wk5hazFRT0hwVWVVUklNMWRUV2xrMlRWUmxSSEZVVTJSNFRRPT0iCiAgICB9CiAgfQp9Cg==

type: kubernetes.io/dockerconfigjson
