apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: IHsKICAiYXV0aHMiOiB7CiAgICAiZ2hjci5pbyI6IHsKICAgICAgImF1dGgiOiAiYTJsd2NtOXJiM0JsYm10dk9tZG9jRjl6VG1sVWVFcDRkM0F3Y1VSb1FuaGlORzlwYUdSMlZraDBlbXhuZUdvemIybEkiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
